ktor:
  development: true
  application:
    modules:
      - com.example.ApplicationKt.module
  deployment:
    port: 8080
api:
  trace_500_error: true
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
  secret: "myStrongSecret"
  ttl: 60000
