POST {{host}}/api/auth
Accept: application/json
Content-Type: application/json

{"login":"user2", "password":"password2"}

> {%
    client.global.set("auth_token", response.body.token);
%}
###

GET {{host}}/api/profile
Authorization: Bearer {{auth_token}}
