POST {{host}}/api/v1/user/auth
Accept: application/json
Content-Type: application/json

{"login":"user2", "password":"password2"}

> {%
    client.global.set("auth_token", response.body.token);
%}
###

GET {{host}}/api/v1/user/profile
Authorization: Bearer {{auth_token}}

###

POST {{host}}/api/v1/user/profile
Authorization: Bearer {{auth_token}}

hello
###

WEBSOCKET {{ws}}/ws

hello
===
hello2
===
hello3
=== wait-for-server
=== wait-for-server
=== wait-for-server
bye
###

GET {{host}}/session/increment

###